#!/usr/bin/env bash


option1=" Connect VPN"
option2=" Disconnect VPN"
option3=" Cancel"
options="$option1\n$option2\n$option3"

action=$(echo -e "$options" | rofi -dmenu -b -l 3 -i -p "🛡 ")
case "$action" in
  $option1*)
      expressvpnctl connect smart;;
  $option2*)
      expressvpnctl disconnect;;
  $option3*)
    exit 0
esac
